TCRI_PARAMETERS = {
    "var_ABSV": "on",
    "var_LAND": "on",
    "var_PWAT": "on",
    "var_RH": "on",
    "var_TMP": "on",
    "var_UGRD": "on",
    "var_VGRD": "on",
    "lev_10_m_above_ground": "on",
    "lev_850_mb": "on",
    "lev_700_mb": "on",
    "lev_200_mb": "on",
    "lev_surface": "on",
    "lev_entire_atmosphere_(considered_as_a_single_layer)": "on",
}
